import { default as ErrorRpcSDKManageActivityActive } from './ErrorRpcSDKManageActivityActive';
import { default as ErrorRpcSDKManageActivityActiveCardAdd } from './ErrorRpcSDKManageActivityActiveCardAdd';
import { default as ErrorRpcSDKManageActivityActiveCardModify } from './ErrorRpcSDKManageActivityActiveCardModify';
import { default as ErrorRpcSDKManageActivityActiveCardQuery } from './ErrorRpcSDKManageActivityActiveCardQuery';
import { default as ErrorRpcSDKManageActivityDelete } from './ErrorRpcSDKManageActivityDelete';
import { default as ErrorRpcSDKManageActivityInvalid } from './ErrorRpcSDKManageActivityInvalid';
import { default as ErrorRpcSDKManageActivityRechargeRebateAdd } from './ErrorRpcSDKManageActivityRechargeRebateAdd';
import { default as ErrorRpcSDKManageActivityRechargeRebateModify } from './ErrorRpcSDKManageActivityRechargeRebateModify';
import { default as ErrorRpcSDKManageActivityRechargeRebateQuery } from './ErrorRpcSDKManageActivityRechargeRebateQuery';
import { default as ErrorRpcSDKManageAuthLogout } from './ErrorRpcSDKManageAuthLogout';
import { default as ErrorRpcSDKManageCardTypeAdd } from './ErrorRpcSDKManageCardTypeAdd';
import { default as ErrorRpcSDKManageCardTypeDelete } from './ErrorRpcSDKManageCardTypeDelete';
import { default as ErrorRpcSDKManageCardTypeModify } from './ErrorRpcSDKManageCardTypeModify';
import { default as ErrorRpcSDKManageCardTypeQuery } from './ErrorRpcSDKManageCardTypeQuery';
import { default as ErrorRpcSDKManageDiscountMerchantAdd } from './ErrorRpcSDKManageDiscountMerchantAdd';
import { default as ErrorRpcSDKManageDiscountMerchantModify } from './ErrorRpcSDKManageDiscountMerchantModify';
import { default as ErrorRpcSDKManageDiscountMerchantQuery } from './ErrorRpcSDKManageDiscountMerchantQuery';
import { default as ErrorRpcSDKManageDiscountPaymentAdd } from './ErrorRpcSDKManageDiscountPaymentAdd';
import { default as ErrorRpcSDKManageDiscountPaymentModify } from './ErrorRpcSDKManageDiscountPaymentModify';
import { default as ErrorRpcSDKManageDiscountPaymentQuery } from './ErrorRpcSDKManageDiscountPaymentQuery';
import { default as ErrorRpcSDKManageDiscountQueryByMerchant } from './ErrorRpcSDKManageDiscountQueryByMerchant';
import { default as ErrorRpcSDKManageFactorageConsumptionModify } from './ErrorRpcSDKManageFactorageConsumptionModify';
import { default as ErrorRpcSDKManageFactorageConsumptionQuery } from './ErrorRpcSDKManageFactorageConsumptionQuery';
import { default as ErrorRpcSDKManageFactorageQueryByMerchant } from './ErrorRpcSDKManageFactorageQueryByMerchant';
import { default as ErrorRpcSDKManageFactorageRechargeModify } from './ErrorRpcSDKManageFactorageRechargeModify';
import { default as ErrorRpcSDKManageFactorageRechargeQuery } from './ErrorRpcSDKManageFactorageRechargeQuery';
import { default as ErrorRpcSDKManageFactorageThirdPartyModify } from './ErrorRpcSDKManageFactorageThirdPartyModify';
import { default as ErrorRpcSDKManageFactorageThirdPartyQuery } from './ErrorRpcSDKManageFactorageThirdPartyQuery';
import { default as ErrorRpcSDKManageFinancePointsMakeUpMiniPoints } from './ErrorRpcSDKManageFinancePointsMakeUpMiniPoints';
import { default as ErrorRpcSDKManageFinancePointsMakeUpPointsToMerchantAccount } from './ErrorRpcSDKManageFinancePointsMakeUpPointsToMerchantAccount';
import { default as ErrorRpcSDKManageFinancePointsMakeUpPointsToPrepaidCard } from './ErrorRpcSDKManageFinancePointsMakeUpPointsToPrepaidCard';
import { default as ErrorRpcSDKManageFinanceProfitSharingModify } from './ErrorRpcSDKManageFinanceProfitSharingModify';
import { default as ErrorRpcSDKManageFinanceProfitSharingQuery } from './ErrorRpcSDKManageFinanceProfitSharingQuery';
import { default as ErrorRpcSDKManageLogin } from './ErrorRpcSDKManageLogin';
import { default as ErrorRpcSDKManageLoginWeiXinMerchant } from './ErrorRpcSDKManageLoginWeiXinMerchant';
import { default as ErrorRpcSDKManageLoginWithCellphoneVerifyCode } from './ErrorRpcSDKManageLoginWithCellphoneVerifyCode';
import { default as ErrorRpcSDKManageLoginWithRefreshToken } from './ErrorRpcSDKManageLoginWithRefreshToken';
import { default as ErrorRpcSDKManageLoginWithSecretKey } from './ErrorRpcSDKManageLoginWithSecretKey';
import { default as ErrorRpcSDKManageMemberFreeze } from './ErrorRpcSDKManageMemberFreeze';
import { default as ErrorRpcSDKManageMemberMerchantAccountAddMerchantMemberAccount } from './ErrorRpcSDKManageMemberMerchantAccountAddMerchantMemberAccount';
import { default as ErrorRpcSDKManageMemberMerchantAccountModifyMemberGenerateChannel } from './ErrorRpcSDKManageMemberMerchantAccountModifyMemberGenerateChannel';
import { default as ErrorRpcSDKManageMemberMerchantAccountQuery } from './ErrorRpcSDKManageMemberMerchantAccountQuery';
import { default as ErrorRpcSDKManageMemberModify } from './ErrorRpcSDKManageMemberModify';
import { default as ErrorRpcSDKManageMemberPaymentModifyLittleFeeFreePasswordStatus } from './ErrorRpcSDKManageMemberPaymentModifyLittleFeeFreePasswordStatus';
import { default as ErrorRpcSDKManageMemberPaymentModifyPayPwd } from './ErrorRpcSDKManageMemberPaymentModifyPayPwd';
import { default as ErrorRpcSDKManageMemberPaymentResetPayPassword } from './ErrorRpcSDKManageMemberPaymentResetPayPassword';
import { default as ErrorRpcSDKManageMemberPaymentSetLittleFeeFreePasswordLimit } from './ErrorRpcSDKManageMemberPaymentSetLittleFeeFreePasswordLimit';
import { default as ErrorRpcSDKManageMemberQuery } from './ErrorRpcSDKManageMemberQuery';
import { default as ErrorRpcSDKManageMemberQueryMemberDetail } from './ErrorRpcSDKManageMemberQueryMemberDetail';
import { default as ErrorRpcSDKManageMemberQueryMerchantMember } from './ErrorRpcSDKManageMemberQueryMerchantMember';
import { default as ErrorRpcSDKManageMemberRealNameCertification } from './ErrorRpcSDKManageMemberRealNameCertification';
import { default as ErrorRpcSDKManageMemberRegister } from './ErrorRpcSDKManageMemberRegister';
import { default as ErrorRpcSDKManageMemberRegisterMerchantMember } from './ErrorRpcSDKManageMemberRegisterMerchantMember';
import { default as ErrorRpcSDKManageMemberUnFreeze } from './ErrorRpcSDKManageMemberUnFreeze';
import { default as ErrorRpcSDKManageMerchantAdd } from './ErrorRpcSDKManageMerchantAdd';
import { default as ErrorRpcSDKManageMerchantChannelAdd } from './ErrorRpcSDKManageMerchantChannelAdd';
import { default as ErrorRpcSDKManageMerchantChannelModify } from './ErrorRpcSDKManageMerchantChannelModify';
import { default as ErrorRpcSDKManageMerchantChannelQuery } from './ErrorRpcSDKManageMerchantChannelQuery';
import { default as ErrorRpcSDKManageMerchantDelete } from './ErrorRpcSDKManageMerchantDelete';
import { default as ErrorRpcSDKManageMerchantFreeze } from './ErrorRpcSDKManageMerchantFreeze';
import { default as ErrorRpcSDKManageMerchantModify } from './ErrorRpcSDKManageMerchantModify';
import { default as ErrorRpcSDKManageMerchantPaymentIDAdd } from './ErrorRpcSDKManageMerchantPaymentIDAdd';
import { default as ErrorRpcSDKManageMerchantPaymentIDModify } from './ErrorRpcSDKManageMerchantPaymentIDModify';
import { default as ErrorRpcSDKManageMerchantQuery } from './ErrorRpcSDKManageMerchantQuery';
import { default as ErrorRpcSDKManageMerchantQueryMerchantDetail } from './ErrorRpcSDKManageMerchantQueryMerchantDetail';
import { default as ErrorRpcSDKManageMerchantQueryReview } from './ErrorRpcSDKManageMerchantQueryReview';
import { default as ErrorRpcSDKManageMerchantUnFreeze } from './ErrorRpcSDKManageMerchantUnFreeze';
import { default as ErrorRpcSDKManageMerchantPointsAdd } from './ErrorRpcSDKManageMerchantPointsAdd';
import { default as ErrorRpcSDKManageMerchantPointsDelete } from './ErrorRpcSDKManageMerchantPointsDelete';
import { default as ErrorRpcSDKManageMerchantPointsModify } from './ErrorRpcSDKManageMerchantPointsModify';
import { default as ErrorRpcSDKManageMerchantPointsQuery } from './ErrorRpcSDKManageMerchantPointsQuery';
import { default as ErrorRpcSDKManageMiniPayPlatformCreate } from './ErrorRpcSDKManageMiniPayPlatformCreate';
import { default as ErrorRpcSDKManageOrganizationAdd } from './ErrorRpcSDKManageOrganizationAdd';
import { default as ErrorRpcSDKManageOrganizationAddMerchant } from './ErrorRpcSDKManageOrganizationAddMerchant';
import { default as ErrorRpcSDKManageOrganizationDelete } from './ErrorRpcSDKManageOrganizationDelete';
import { default as ErrorRpcSDKManageOrganizationModify } from './ErrorRpcSDKManageOrganizationModify';
import { default as ErrorRpcSDKManageOrganizationModifyHeadquarter } from './ErrorRpcSDKManageOrganizationModifyHeadquarter';
import { default as ErrorRpcSDKManageOrganizationModifyMerchant } from './ErrorRpcSDKManageOrganizationModifyMerchant';
import { default as ErrorRpcSDKManageOrganizationQuery } from './ErrorRpcSDKManageOrganizationQuery';
import { default as ErrorRpcSDKManageOrganizationQueryDetail } from './ErrorRpcSDKManageOrganizationQueryDetail';
import { default as ErrorRpcSDKManageOrganizationRemoveMerchant } from './ErrorRpcSDKManageOrganizationRemoveMerchant';
import { default as ErrorRpcSDKManagePaymentAccountTransferAdd } from './ErrorRpcSDKManagePaymentAccountTransferAdd';
import { default as ErrorRpcSDKManagePaymentAccountTransferDelete } from './ErrorRpcSDKManagePaymentAccountTransferDelete';
import { default as ErrorRpcSDKManagePaymentAccountTransferModify } from './ErrorRpcSDKManagePaymentAccountTransferModify';
import { default as ErrorRpcSDKManagePaymentAuth20Add } from './ErrorRpcSDKManagePaymentAuth20Add';
import { default as ErrorRpcSDKManagePaymentAuth20Delete } from './ErrorRpcSDKManagePaymentAuth20Delete';
import { default as ErrorRpcSDKManagePaymentAuth20Modify } from './ErrorRpcSDKManagePaymentAuth20Modify';
import { default as ErrorRpcSDKManagePaymentNetPayAdd } from './ErrorRpcSDKManagePaymentNetPayAdd';
import { default as ErrorRpcSDKManagePaymentNetPayDelete } from './ErrorRpcSDKManagePaymentNetPayDelete';
import { default as ErrorRpcSDKManagePaymentNetPayModify } from './ErrorRpcSDKManagePaymentNetPayModify';
import { default as ErrorRpcSDKManagePaymentNoCardPayAdd } from './ErrorRpcSDKManagePaymentNoCardPayAdd';
import { default as ErrorRpcSDKManagePaymentNoCardPayDelete } from './ErrorRpcSDKManagePaymentNoCardPayDelete';
import { default as ErrorRpcSDKManagePaymentNoCardPayModify } from './ErrorRpcSDKManagePaymentNoCardPayModify';
import { default as ErrorRpcSDKManagePaymentOnlineRechargeAdd } from './ErrorRpcSDKManagePaymentOnlineRechargeAdd';
import { default as ErrorRpcSDKManagePaymentOnlineRechargeAddQuota } from './ErrorRpcSDKManagePaymentOnlineRechargeAddQuota';
import { default as ErrorRpcSDKManagePaymentOnlineRechargeDelete } from './ErrorRpcSDKManagePaymentOnlineRechargeDelete';
import { default as ErrorRpcSDKManagePaymentOnlineRechargeQueryChange } from './ErrorRpcSDKManagePaymentOnlineRechargeQueryChange';
import { default as ErrorRpcSDKManagePaymentOnlineRechargeQueryQuotaConsumeTransaction } from './ErrorRpcSDKManagePaymentOnlineRechargeQueryQuotaConsumeTransaction';
import { default as ErrorRpcSDKManagePaymentOnlineRechargeQueryQuotaRechargeTransaction } from './ErrorRpcSDKManagePaymentOnlineRechargeQueryQuotaRechargeTransaction';
import { default as ErrorRpcSDKManagePaymentPosAdd } from './ErrorRpcSDKManagePaymentPosAdd';
import { default as ErrorRpcSDKManagePaymentPosDelete } from './ErrorRpcSDKManagePaymentPosDelete';
import { default as ErrorRpcSDKManagePaymentPosDetail } from './ErrorRpcSDKManagePaymentPosDetail';
import { default as ErrorRpcSDKManagePaymentPosExport } from './ErrorRpcSDKManagePaymentPosExport';
import { default as ErrorRpcSDKManagePaymentPosModify } from './ErrorRpcSDKManagePaymentPosModify';
import { default as ErrorRpcSDKManagePaymentPosQuery } from './ErrorRpcSDKManagePaymentPosQuery';
import { default as ErrorRpcSDKManagePaymentQuery } from './ErrorRpcSDKManagePaymentQuery';
import { default as ErrorRpcSDKManagePermissionAdd } from './ErrorRpcSDKManagePermissionAdd';
import { default as ErrorRpcSDKManagePermissionDelete } from './ErrorRpcSDKManagePermissionDelete';
import { default as ErrorRpcSDKManagePermissionQuery } from './ErrorRpcSDKManagePermissionQuery';
import { default as ErrorRpcSDKManagePrePaidCardCardBinApplyEntityCardBin } from './ErrorRpcSDKManagePrePaidCardCardBinApplyEntityCardBin';
import { default as ErrorRpcSDKManagePrePaidCardCardBinQuery } from './ErrorRpcSDKManagePrePaidCardCardBinQuery';
import { default as ErrorRpcSDKManagePrePaidCardFabricationApply } from './ErrorRpcSDKManagePrePaidCardFabricationApply';
import { default as ErrorRpcSDKManagePrePaidCardFabricationDelete } from './ErrorRpcSDKManagePrePaidCardFabricationDelete';
import { default as ErrorRpcSDKManagePrePaidCardFabricationExport } from './ErrorRpcSDKManagePrePaidCardFabricationExport';
import { default as ErrorRpcSDKManagePrePaidCardFabricationInformationQueryFabricationDetail } from './ErrorRpcSDKManagePrePaidCardFabricationInformationQueryFabricationDetail';
import { default as ErrorRpcSDKManagePrePaidCardFabricationMake } from './ErrorRpcSDKManagePrePaidCardFabricationMake';
import { default as ErrorRpcSDKManagePrePaidCardFabricationQuery } from './ErrorRpcSDKManagePrePaidCardFabricationQuery';
import { default as ErrorRpcSDKManagePrePaidCardQuery } from './ErrorRpcSDKManagePrePaidCardQuery';
import { default as ErrorRpcSDKManagePrePaidCardTradeOnlineRechargeBatch } from './ErrorRpcSDKManagePrePaidCardTradeOnlineRechargeBatch';
import { default as ErrorRpcSDKManagePrePaidCardTradeOnlineRechargeSingle } from './ErrorRpcSDKManagePrePaidCardTradeOnlineRechargeSingle';
import { default as ErrorRpcSDKManagePrePaidCardTradeReDrawBatch } from './ErrorRpcSDKManagePrePaidCardTradeReDrawBatch';
import { default as ErrorRpcSDKManagePrePaidCardTradeReDrawSingle } from './ErrorRpcSDKManagePrePaidCardTradeReDrawSingle';
import { default as ErrorRpcSDKManagePrePaidCardTradeSellCard } from './ErrorRpcSDKManagePrePaidCardTradeSellCard';
import { default as ErrorRpcSDKManagePrePaidCardTradeSellCardByCellphone } from './ErrorRpcSDKManagePrePaidCardTradeSellCardByCellphone';
import { default as ErrorRpcSDKManagePrePaidCardTradeSellVirtualCard } from './ErrorRpcSDKManagePrePaidCardTradeSellVirtualCard';
import { default as ErrorRpcSDKManagePrePaidCardTradeSellVirtualCardWithCellphone } from './ErrorRpcSDKManagePrePaidCardTradeSellVirtualCardWithCellphone';
import { default as ErrorRpcSDKManagePrePaidCardTradeTransferAccount } from './ErrorRpcSDKManagePrePaidCardTradeTransferAccount';
import { default as ErrorRpcSDKManagePrePaidCardUsageActive } from './ErrorRpcSDKManagePrePaidCardUsageActive';
import { default as ErrorRpcSDKManagePrePaidCardUsageBindToMember } from './ErrorRpcSDKManagePrePaidCardUsageBindToMember';
import { default as ErrorRpcSDKManagePrePaidCardUsageDeActivate } from './ErrorRpcSDKManagePrePaidCardUsageDeActivate';
import { default as ErrorRpcSDKManagePrePaidCardUsageExportActiveCard } from './ErrorRpcSDKManagePrePaidCardUsageExportActiveCard';
import { default as ErrorRpcSDKManagePrePaidCardUsageFreeze } from './ErrorRpcSDKManagePrePaidCardUsageFreeze';
import { default as ErrorRpcSDKManagePrePaidCardUsageMakeUpCard } from './ErrorRpcSDKManagePrePaidCardUsageMakeUpCard';
import { default as ErrorRpcSDKManagePrePaidCardUsageModifyPassword } from './ErrorRpcSDKManagePrePaidCardUsageModifyPassword';
import { default as ErrorRpcSDKManagePrePaidCardUsageResetPassword } from './ErrorRpcSDKManagePrePaidCardUsageResetPassword';
import { default as ErrorRpcSDKManagePrePaidCardUsageUnBind } from './ErrorRpcSDKManagePrePaidCardUsageUnBind';
import { default as ErrorRpcSDKManagePrePaidCardUsageUnFreeze } from './ErrorRpcSDKManagePrePaidCardUsageUnFreeze';
import { default as ErrorRpcSDKManageProfitSharingSalesmanAdd } from './ErrorRpcSDKManageProfitSharingSalesmanAdd';
import { default as ErrorRpcSDKManageProfitSharingSalesmanDelete } from './ErrorRpcSDKManageProfitSharingSalesmanDelete';
import { default as ErrorRpcSDKManageProfitSharingSalesmanModify } from './ErrorRpcSDKManageProfitSharingSalesmanModify';
import { default as ErrorRpcSDKManageProfitSharingSalesmanQueryByMember } from './ErrorRpcSDKManageProfitSharingSalesmanQueryByMember';
import { default as ErrorRpcSDKManageProfitSharingSalesmanQueryByMerchant } from './ErrorRpcSDKManageProfitSharingSalesmanQueryByMerchant';
import { default as ErrorRpcSDKManageRequestVerify } from './ErrorRpcSDKManageRequestVerify';
import { default as ErrorRpcSDKManageReviewActivityQuery } from './ErrorRpcSDKManageReviewActivityQuery';
import { default as ErrorRpcSDKManageReviewDelete } from './ErrorRpcSDKManageReviewDelete';
import { default as ErrorRpcSDKManageReviewFabricationCardQuery } from './ErrorRpcSDKManageReviewFabricationCardQuery';
import { default as ErrorRpcSDKManageReviewFactorageQuery } from './ErrorRpcSDKManageReviewFactorageQuery';
import { default as ErrorRpcSDKManageReviewModify } from './ErrorRpcSDKManageReviewModify';
import { default as ErrorRpcSDKManageReviewPaymentProductQuery } from './ErrorRpcSDKManageReviewPaymentProductQuery';
import { default as ErrorRpcSDKManageReviewPermissionAdd } from './ErrorRpcSDKManageReviewPermissionAdd';
import { default as ErrorRpcSDKManageReviewPermissionDelete } from './ErrorRpcSDKManageReviewPermissionDelete';
import { default as ErrorRpcSDKManageReviewPermissionFreeze } from './ErrorRpcSDKManageReviewPermissionFreeze';
import { default as ErrorRpcSDKManageReviewPermissionQuery } from './ErrorRpcSDKManageReviewPermissionQuery';
import { default as ErrorRpcSDKManageReviewPermissionUnFreeze } from './ErrorRpcSDKManageReviewPermissionUnFreeze';
import { default as ErrorRpcSDKManageReviewQueryCenterReview } from './ErrorRpcSDKManageReviewQueryCenterReview';
import { default as ErrorRpcSDKManageReviewQuerySDKManageReview } from './ErrorRpcSDKManageReviewQuerySDKManageReview';
import { default as ErrorRpcSDKManageReviewReview } from './ErrorRpcSDKManageReviewReview';
import { default as ErrorRpcSDKManageSmsRequestLoginVerifyCodeWithUserName } from './ErrorRpcSDKManageSmsRequestLoginVerifyCodeWithUserName';
import { default as ErrorRpcSDKManageSmsRequestVerify } from './ErrorRpcSDKManageSmsRequestVerify';
import { default as ErrorRpcSDKManageSystemAlarmDelete } from './ErrorRpcSDKManageSystemAlarmDelete';
import { default as ErrorRpcSDKManageSystemAlarmDetail } from './ErrorRpcSDKManageSystemAlarmDetail';
import { default as ErrorRpcSDKManageSystemAlarmModify } from './ErrorRpcSDKManageSystemAlarmModify';
import { default as ErrorRpcSDKManageSystemAlarmQuery } from './ErrorRpcSDKManageSystemAlarmQuery';
import { default as ErrorRpcSDKManageSystemMessageDelete } from './ErrorRpcSDKManageSystemMessageDelete';
import { default as ErrorRpcSDKManageSystemMessageMark } from './ErrorRpcSDKManageSystemMessageMark';
import { default as ErrorRpcSDKManageSystemMessageQuery } from './ErrorRpcSDKManageSystemMessageQuery';
import { default as ErrorRpcSDKManageSystemMessageSend } from './ErrorRpcSDKManageSystemMessageSend';
import { default as ErrorRpcSDKManageSystemNoticeAdd } from './ErrorRpcSDKManageSystemNoticeAdd';
import { default as ErrorRpcSDKManageSystemNoticeDelete } from './ErrorRpcSDKManageSystemNoticeDelete';
import { default as ErrorRpcSDKManageSystemNoticeModify } from './ErrorRpcSDKManageSystemNoticeModify';
import { default as ErrorRpcSDKManageSystemNoticeQuery } from './ErrorRpcSDKManageSystemNoticeQuery';
import { default as ErrorRpcSDKManageTokenGetAccessToken } from './ErrorRpcSDKManageTokenGetAccessToken';
import { default as ErrorRpcSDKManageTokenGetRefreshToken } from './ErrorRpcSDKManageTokenGetRefreshToken';
import { default as ErrorRpcSDKManageTransactionConsumptionExport } from './ErrorRpcSDKManageTransactionConsumptionExport';
import { default as ErrorRpcSDKManageTransactionMakeUpPosMachineRecharge } from './ErrorRpcSDKManageTransactionMakeUpPosMachineRecharge';
import { default as ErrorRpcSDKManageTransactionQuery } from './ErrorRpcSDKManageTransactionQuery';
import { default as ErrorRpcSDKManageTransactionRechargeReconcilation } from './ErrorRpcSDKManageTransactionRechargeReconcilation';
import { default as ErrorRpcSDKManageUserAdd } from './ErrorRpcSDKManageUserAdd';
import { default as ErrorRpcSDKManageUserAddPermission } from './ErrorRpcSDKManageUserAddPermission';
import { default as ErrorRpcSDKManageUserDelete } from './ErrorRpcSDKManageUserDelete';
import { default as ErrorRpcSDKManageUserDeletePermission } from './ErrorRpcSDKManageUserDeletePermission';
import { default as ErrorRpcSDKManageUserFreeze } from './ErrorRpcSDKManageUserFreeze';
import { default as ErrorRpcSDKManageUserGetPermission } from './ErrorRpcSDKManageUserGetPermission';
import { default as ErrorRpcSDKManageUserModifyPassword } from './ErrorRpcSDKManageUserModifyPassword';
import { default as ErrorRpcSDKManageUserQuery } from './ErrorRpcSDKManageUserQuery';
import { default as ErrorRpcSDKManageUserResetLoginPasswordWithSms } from './ErrorRpcSDKManageUserResetLoginPasswordWithSms';
import { default as ErrorRpcSDKManageUserUnFreeze } from './ErrorRpcSDKManageUserUnFreeze';

let CodesMap = {};
CodesMap[ErrorRpcSDKManageActivityActive.method] = ErrorRpcSDKManageActivityActive.codes;
CodesMap[ErrorRpcSDKManageActivityActiveCardAdd.method] = ErrorRpcSDKManageActivityActiveCardAdd.codes;
CodesMap[ErrorRpcSDKManageActivityActiveCardModify.method] = ErrorRpcSDKManageActivityActiveCardModify.codes;
CodesMap[ErrorRpcSDKManageActivityActiveCardQuery.method] = ErrorRpcSDKManageActivityActiveCardQuery.codes;
CodesMap[ErrorRpcSDKManageActivityDelete.method] = ErrorRpcSDKManageActivityDelete.codes;
CodesMap[ErrorRpcSDKManageActivityInvalid.method] = ErrorRpcSDKManageActivityInvalid.codes;
CodesMap[ErrorRpcSDKManageActivityRechargeRebateAdd.method] = ErrorRpcSDKManageActivityRechargeRebateAdd.codes;
CodesMap[ErrorRpcSDKManageActivityRechargeRebateModify.method] = ErrorRpcSDKManageActivityRechargeRebateModify.codes;
CodesMap[ErrorRpcSDKManageActivityRechargeRebateQuery.method] = ErrorRpcSDKManageActivityRechargeRebateQuery.codes;
CodesMap[ErrorRpcSDKManageAuthLogout.method] = ErrorRpcSDKManageAuthLogout.codes;
CodesMap[ErrorRpcSDKManageCardTypeAdd.method] = ErrorRpcSDKManageCardTypeAdd.codes;
CodesMap[ErrorRpcSDKManageCardTypeDelete.method] = ErrorRpcSDKManageCardTypeDelete.codes;
CodesMap[ErrorRpcSDKManageCardTypeModify.method] = ErrorRpcSDKManageCardTypeModify.codes;
CodesMap[ErrorRpcSDKManageCardTypeQuery.method] = ErrorRpcSDKManageCardTypeQuery.codes;
CodesMap[ErrorRpcSDKManageDiscountMerchantAdd.method] = ErrorRpcSDKManageDiscountMerchantAdd.codes;
CodesMap[ErrorRpcSDKManageDiscountMerchantModify.method] = ErrorRpcSDKManageDiscountMerchantModify.codes;
CodesMap[ErrorRpcSDKManageDiscountMerchantQuery.method] = ErrorRpcSDKManageDiscountMerchantQuery.codes;
CodesMap[ErrorRpcSDKManageDiscountPaymentAdd.method] = ErrorRpcSDKManageDiscountPaymentAdd.codes;
CodesMap[ErrorRpcSDKManageDiscountPaymentModify.method] = ErrorRpcSDKManageDiscountPaymentModify.codes;
CodesMap[ErrorRpcSDKManageDiscountPaymentQuery.method] = ErrorRpcSDKManageDiscountPaymentQuery.codes;
CodesMap[ErrorRpcSDKManageDiscountQueryByMerchant.method] = ErrorRpcSDKManageDiscountQueryByMerchant.codes;
CodesMap[ErrorRpcSDKManageFactorageConsumptionModify.method] = ErrorRpcSDKManageFactorageConsumptionModify.codes;
CodesMap[ErrorRpcSDKManageFactorageConsumptionQuery.method] = ErrorRpcSDKManageFactorageConsumptionQuery.codes;
CodesMap[ErrorRpcSDKManageFactorageQueryByMerchant.method] = ErrorRpcSDKManageFactorageQueryByMerchant.codes;
CodesMap[ErrorRpcSDKManageFactorageRechargeModify.method] = ErrorRpcSDKManageFactorageRechargeModify.codes;
CodesMap[ErrorRpcSDKManageFactorageRechargeQuery.method] = ErrorRpcSDKManageFactorageRechargeQuery.codes;
CodesMap[ErrorRpcSDKManageFactorageThirdPartyModify.method] = ErrorRpcSDKManageFactorageThirdPartyModify.codes;
CodesMap[ErrorRpcSDKManageFactorageThirdPartyQuery.method] = ErrorRpcSDKManageFactorageThirdPartyQuery.codes;
CodesMap[ErrorRpcSDKManageFinancePointsMakeUpMiniPoints.method] = ErrorRpcSDKManageFinancePointsMakeUpMiniPoints.codes;
CodesMap[ErrorRpcSDKManageFinancePointsMakeUpPointsToMerchantAccount.method] = ErrorRpcSDKManageFinancePointsMakeUpPointsToMerchantAccount.codes;
CodesMap[ErrorRpcSDKManageFinancePointsMakeUpPointsToPrepaidCard.method] = ErrorRpcSDKManageFinancePointsMakeUpPointsToPrepaidCard.codes;
CodesMap[ErrorRpcSDKManageFinanceProfitSharingModify.method] = ErrorRpcSDKManageFinanceProfitSharingModify.codes;
CodesMap[ErrorRpcSDKManageFinanceProfitSharingQuery.method] = ErrorRpcSDKManageFinanceProfitSharingQuery.codes;
CodesMap[ErrorRpcSDKManageLogin.method] = ErrorRpcSDKManageLogin.codes;
CodesMap[ErrorRpcSDKManageLoginWeiXinMerchant.method] = ErrorRpcSDKManageLoginWeiXinMerchant.codes;
CodesMap[ErrorRpcSDKManageLoginWithCellphoneVerifyCode.method] = ErrorRpcSDKManageLoginWithCellphoneVerifyCode.codes;
CodesMap[ErrorRpcSDKManageLoginWithRefreshToken.method] = ErrorRpcSDKManageLoginWithRefreshToken.codes;
CodesMap[ErrorRpcSDKManageLoginWithSecretKey.method] = ErrorRpcSDKManageLoginWithSecretKey.codes;
CodesMap[ErrorRpcSDKManageMemberFreeze.method] = ErrorRpcSDKManageMemberFreeze.codes;
CodesMap[ErrorRpcSDKManageMemberMerchantAccountAddMerchantMemberAccount.method] = ErrorRpcSDKManageMemberMerchantAccountAddMerchantMemberAccount.codes;
CodesMap[ErrorRpcSDKManageMemberMerchantAccountModifyMemberGenerateChannel.method] = ErrorRpcSDKManageMemberMerchantAccountModifyMemberGenerateChannel.codes;
CodesMap[ErrorRpcSDKManageMemberMerchantAccountQuery.method] = ErrorRpcSDKManageMemberMerchantAccountQuery.codes;
CodesMap[ErrorRpcSDKManageMemberModify.method] = ErrorRpcSDKManageMemberModify.codes;
CodesMap[ErrorRpcSDKManageMemberPaymentModifyLittleFeeFreePasswordStatus.method] = ErrorRpcSDKManageMemberPaymentModifyLittleFeeFreePasswordStatus.codes;
CodesMap[ErrorRpcSDKManageMemberPaymentModifyPayPwd.method] = ErrorRpcSDKManageMemberPaymentModifyPayPwd.codes;
CodesMap[ErrorRpcSDKManageMemberPaymentResetPayPassword.method] = ErrorRpcSDKManageMemberPaymentResetPayPassword.codes;
CodesMap[ErrorRpcSDKManageMemberPaymentSetLittleFeeFreePasswordLimit.method] = ErrorRpcSDKManageMemberPaymentSetLittleFeeFreePasswordLimit.codes;
CodesMap[ErrorRpcSDKManageMemberQuery.method] = ErrorRpcSDKManageMemberQuery.codes;
CodesMap[ErrorRpcSDKManageMemberQueryMemberDetail.method] = ErrorRpcSDKManageMemberQueryMemberDetail.codes;
CodesMap[ErrorRpcSDKManageMemberQueryMerchantMember.method] = ErrorRpcSDKManageMemberQueryMerchantMember.codes;
CodesMap[ErrorRpcSDKManageMemberRealNameCertification.method] = ErrorRpcSDKManageMemberRealNameCertification.codes;
CodesMap[ErrorRpcSDKManageMemberRegister.method] = ErrorRpcSDKManageMemberRegister.codes;
CodesMap[ErrorRpcSDKManageMemberRegisterMerchantMember.method] = ErrorRpcSDKManageMemberRegisterMerchantMember.codes;
CodesMap[ErrorRpcSDKManageMemberUnFreeze.method] = ErrorRpcSDKManageMemberUnFreeze.codes;
CodesMap[ErrorRpcSDKManageMerchantAdd.method] = ErrorRpcSDKManageMerchantAdd.codes;
CodesMap[ErrorRpcSDKManageMerchantChannelAdd.method] = ErrorRpcSDKManageMerchantChannelAdd.codes;
CodesMap[ErrorRpcSDKManageMerchantChannelModify.method] = ErrorRpcSDKManageMerchantChannelModify.codes;
CodesMap[ErrorRpcSDKManageMerchantChannelQuery.method] = ErrorRpcSDKManageMerchantChannelQuery.codes;
CodesMap[ErrorRpcSDKManageMerchantDelete.method] = ErrorRpcSDKManageMerchantDelete.codes;
CodesMap[ErrorRpcSDKManageMerchantFreeze.method] = ErrorRpcSDKManageMerchantFreeze.codes;
CodesMap[ErrorRpcSDKManageMerchantModify.method] = ErrorRpcSDKManageMerchantModify.codes;
CodesMap[ErrorRpcSDKManageMerchantPaymentIDAdd.method] = ErrorRpcSDKManageMerchantPaymentIDAdd.codes;
CodesMap[ErrorRpcSDKManageMerchantPaymentIDModify.method] = ErrorRpcSDKManageMerchantPaymentIDModify.codes;
CodesMap[ErrorRpcSDKManageMerchantQuery.method] = ErrorRpcSDKManageMerchantQuery.codes;
CodesMap[ErrorRpcSDKManageMerchantQueryMerchantDetail.method] = ErrorRpcSDKManageMerchantQueryMerchantDetail.codes;
CodesMap[ErrorRpcSDKManageMerchantQueryReview.method] = ErrorRpcSDKManageMerchantQueryReview.codes;
CodesMap[ErrorRpcSDKManageMerchantUnFreeze.method] = ErrorRpcSDKManageMerchantUnFreeze.codes;
CodesMap[ErrorRpcSDKManageMerchantPointsAdd.method] = ErrorRpcSDKManageMerchantPointsAdd.codes;
CodesMap[ErrorRpcSDKManageMerchantPointsDelete.method] = ErrorRpcSDKManageMerchantPointsDelete.codes;
CodesMap[ErrorRpcSDKManageMerchantPointsModify.method] = ErrorRpcSDKManageMerchantPointsModify.codes;
CodesMap[ErrorRpcSDKManageMerchantPointsQuery.method] = ErrorRpcSDKManageMerchantPointsQuery.codes;
CodesMap[ErrorRpcSDKManageMiniPayPlatformCreate.method] = ErrorRpcSDKManageMiniPayPlatformCreate.codes;
CodesMap[ErrorRpcSDKManageOrganizationAdd.method] = ErrorRpcSDKManageOrganizationAdd.codes;
CodesMap[ErrorRpcSDKManageOrganizationAddMerchant.method] = ErrorRpcSDKManageOrganizationAddMerchant.codes;
CodesMap[ErrorRpcSDKManageOrganizationDelete.method] = ErrorRpcSDKManageOrganizationDelete.codes;
CodesMap[ErrorRpcSDKManageOrganizationModify.method] = ErrorRpcSDKManageOrganizationModify.codes;
CodesMap[ErrorRpcSDKManageOrganizationModifyHeadquarter.method] = ErrorRpcSDKManageOrganizationModifyHeadquarter.codes;
CodesMap[ErrorRpcSDKManageOrganizationModifyMerchant.method] = ErrorRpcSDKManageOrganizationModifyMerchant.codes;
CodesMap[ErrorRpcSDKManageOrganizationQuery.method] = ErrorRpcSDKManageOrganizationQuery.codes;
CodesMap[ErrorRpcSDKManageOrganizationQueryDetail.method] = ErrorRpcSDKManageOrganizationQueryDetail.codes;
CodesMap[ErrorRpcSDKManageOrganizationRemoveMerchant.method] = ErrorRpcSDKManageOrganizationRemoveMerchant.codes;
CodesMap[ErrorRpcSDKManagePaymentAccountTransferAdd.method] = ErrorRpcSDKManagePaymentAccountTransferAdd.codes;
CodesMap[ErrorRpcSDKManagePaymentAccountTransferDelete.method] = ErrorRpcSDKManagePaymentAccountTransferDelete.codes;
CodesMap[ErrorRpcSDKManagePaymentAccountTransferModify.method] = ErrorRpcSDKManagePaymentAccountTransferModify.codes;
CodesMap[ErrorRpcSDKManagePaymentAuth20Add.method] = ErrorRpcSDKManagePaymentAuth20Add.codes;
CodesMap[ErrorRpcSDKManagePaymentAuth20Delete.method] = ErrorRpcSDKManagePaymentAuth20Delete.codes;
CodesMap[ErrorRpcSDKManagePaymentAuth20Modify.method] = ErrorRpcSDKManagePaymentAuth20Modify.codes;
CodesMap[ErrorRpcSDKManagePaymentNetPayAdd.method] = ErrorRpcSDKManagePaymentNetPayAdd.codes;
CodesMap[ErrorRpcSDKManagePaymentNetPayDelete.method] = ErrorRpcSDKManagePaymentNetPayDelete.codes;
CodesMap[ErrorRpcSDKManagePaymentNetPayModify.method] = ErrorRpcSDKManagePaymentNetPayModify.codes;
CodesMap[ErrorRpcSDKManagePaymentNoCardPayAdd.method] = ErrorRpcSDKManagePaymentNoCardPayAdd.codes;
CodesMap[ErrorRpcSDKManagePaymentNoCardPayDelete.method] = ErrorRpcSDKManagePaymentNoCardPayDelete.codes;
CodesMap[ErrorRpcSDKManagePaymentNoCardPayModify.method] = ErrorRpcSDKManagePaymentNoCardPayModify.codes;
CodesMap[ErrorRpcSDKManagePaymentOnlineRechargeAdd.method] = ErrorRpcSDKManagePaymentOnlineRechargeAdd.codes;
CodesMap[ErrorRpcSDKManagePaymentOnlineRechargeAddQuota.method] = ErrorRpcSDKManagePaymentOnlineRechargeAddQuota.codes;
CodesMap[ErrorRpcSDKManagePaymentOnlineRechargeDelete.method] = ErrorRpcSDKManagePaymentOnlineRechargeDelete.codes;
CodesMap[ErrorRpcSDKManagePaymentOnlineRechargeQueryChange.method] = ErrorRpcSDKManagePaymentOnlineRechargeQueryChange.codes;
CodesMap[ErrorRpcSDKManagePaymentOnlineRechargeQueryQuotaConsumeTransaction.method] = ErrorRpcSDKManagePaymentOnlineRechargeQueryQuotaConsumeTransaction.codes;
CodesMap[ErrorRpcSDKManagePaymentOnlineRechargeQueryQuotaRechargeTransaction.method] = ErrorRpcSDKManagePaymentOnlineRechargeQueryQuotaRechargeTransaction.codes;
CodesMap[ErrorRpcSDKManagePaymentPosAdd.method] = ErrorRpcSDKManagePaymentPosAdd.codes;
CodesMap[ErrorRpcSDKManagePaymentPosDelete.method] = ErrorRpcSDKManagePaymentPosDelete.codes;
CodesMap[ErrorRpcSDKManagePaymentPosDetail.method] = ErrorRpcSDKManagePaymentPosDetail.codes;
CodesMap[ErrorRpcSDKManagePaymentPosExport.method] = ErrorRpcSDKManagePaymentPosExport.codes;
CodesMap[ErrorRpcSDKManagePaymentPosModify.method] = ErrorRpcSDKManagePaymentPosModify.codes;
CodesMap[ErrorRpcSDKManagePaymentPosQuery.method] = ErrorRpcSDKManagePaymentPosQuery.codes;
CodesMap[ErrorRpcSDKManagePaymentQuery.method] = ErrorRpcSDKManagePaymentQuery.codes;
CodesMap[ErrorRpcSDKManagePermissionAdd.method] = ErrorRpcSDKManagePermissionAdd.codes;
CodesMap[ErrorRpcSDKManagePermissionDelete.method] = ErrorRpcSDKManagePermissionDelete.codes;
CodesMap[ErrorRpcSDKManagePermissionQuery.method] = ErrorRpcSDKManagePermissionQuery.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardCardBinApplyEntityCardBin.method] = ErrorRpcSDKManagePrePaidCardCardBinApplyEntityCardBin.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardCardBinQuery.method] = ErrorRpcSDKManagePrePaidCardCardBinQuery.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardFabricationApply.method] = ErrorRpcSDKManagePrePaidCardFabricationApply.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardFabricationDelete.method] = ErrorRpcSDKManagePrePaidCardFabricationDelete.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardFabricationExport.method] = ErrorRpcSDKManagePrePaidCardFabricationExport.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardFabricationInformationQueryFabricationDetail.method] = ErrorRpcSDKManagePrePaidCardFabricationInformationQueryFabricationDetail.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardFabricationMake.method] = ErrorRpcSDKManagePrePaidCardFabricationMake.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardFabricationQuery.method] = ErrorRpcSDKManagePrePaidCardFabricationQuery.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardQuery.method] = ErrorRpcSDKManagePrePaidCardQuery.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardTradeOnlineRechargeBatch.method] = ErrorRpcSDKManagePrePaidCardTradeOnlineRechargeBatch.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardTradeOnlineRechargeSingle.method] = ErrorRpcSDKManagePrePaidCardTradeOnlineRechargeSingle.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardTradeReDrawBatch.method] = ErrorRpcSDKManagePrePaidCardTradeReDrawBatch.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardTradeReDrawSingle.method] = ErrorRpcSDKManagePrePaidCardTradeReDrawSingle.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardTradeSellCard.method] = ErrorRpcSDKManagePrePaidCardTradeSellCard.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardTradeSellCardByCellphone.method] = ErrorRpcSDKManagePrePaidCardTradeSellCardByCellphone.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardTradeSellVirtualCard.method] = ErrorRpcSDKManagePrePaidCardTradeSellVirtualCard.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardTradeSellVirtualCardWithCellphone.method] = ErrorRpcSDKManagePrePaidCardTradeSellVirtualCardWithCellphone.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardTradeTransferAccount.method] = ErrorRpcSDKManagePrePaidCardTradeTransferAccount.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardUsageActive.method] = ErrorRpcSDKManagePrePaidCardUsageActive.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardUsageBindToMember.method] = ErrorRpcSDKManagePrePaidCardUsageBindToMember.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardUsageDeActivate.method] = ErrorRpcSDKManagePrePaidCardUsageDeActivate.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardUsageExportActiveCard.method] = ErrorRpcSDKManagePrePaidCardUsageExportActiveCard.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardUsageFreeze.method] = ErrorRpcSDKManagePrePaidCardUsageFreeze.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardUsageMakeUpCard.method] = ErrorRpcSDKManagePrePaidCardUsageMakeUpCard.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardUsageModifyPassword.method] = ErrorRpcSDKManagePrePaidCardUsageModifyPassword.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardUsageResetPassword.method] = ErrorRpcSDKManagePrePaidCardUsageResetPassword.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardUsageUnBind.method] = ErrorRpcSDKManagePrePaidCardUsageUnBind.codes;
CodesMap[ErrorRpcSDKManagePrePaidCardUsageUnFreeze.method] = ErrorRpcSDKManagePrePaidCardUsageUnFreeze.codes;
CodesMap[ErrorRpcSDKManageProfitSharingSalesmanAdd.method] = ErrorRpcSDKManageProfitSharingSalesmanAdd.codes;
CodesMap[ErrorRpcSDKManageProfitSharingSalesmanDelete.method] = ErrorRpcSDKManageProfitSharingSalesmanDelete.codes;
CodesMap[ErrorRpcSDKManageProfitSharingSalesmanModify.method] = ErrorRpcSDKManageProfitSharingSalesmanModify.codes;
CodesMap[ErrorRpcSDKManageProfitSharingSalesmanQueryByMember.method] = ErrorRpcSDKManageProfitSharingSalesmanQueryByMember.codes;
CodesMap[ErrorRpcSDKManageProfitSharingSalesmanQueryByMerchant.method] = ErrorRpcSDKManageProfitSharingSalesmanQueryByMerchant.codes;
CodesMap[ErrorRpcSDKManageRequestVerify.method] = ErrorRpcSDKManageRequestVerify.codes;
CodesMap[ErrorRpcSDKManageReviewActivityQuery.method] = ErrorRpcSDKManageReviewActivityQuery.codes;
CodesMap[ErrorRpcSDKManageReviewDelete.method] = ErrorRpcSDKManageReviewDelete.codes;
CodesMap[ErrorRpcSDKManageReviewFabricationCardQuery.method] = ErrorRpcSDKManageReviewFabricationCardQuery.codes;
CodesMap[ErrorRpcSDKManageReviewFactorageQuery.method] = ErrorRpcSDKManageReviewFactorageQuery.codes;
CodesMap[ErrorRpcSDKManageReviewModify.method] = ErrorRpcSDKManageReviewModify.codes;
CodesMap[ErrorRpcSDKManageReviewPaymentProductQuery.method] = ErrorRpcSDKManageReviewPaymentProductQuery.codes;
CodesMap[ErrorRpcSDKManageReviewPermissionAdd.method] = ErrorRpcSDKManageReviewPermissionAdd.codes;
CodesMap[ErrorRpcSDKManageReviewPermissionDelete.method] = ErrorRpcSDKManageReviewPermissionDelete.codes;
CodesMap[ErrorRpcSDKManageReviewPermissionFreeze.method] = ErrorRpcSDKManageReviewPermissionFreeze.codes;
CodesMap[ErrorRpcSDKManageReviewPermissionQuery.method] = ErrorRpcSDKManageReviewPermissionQuery.codes;
CodesMap[ErrorRpcSDKManageReviewPermissionUnFreeze.method] = ErrorRpcSDKManageReviewPermissionUnFreeze.codes;
CodesMap[ErrorRpcSDKManageReviewQueryCenterReview.method] = ErrorRpcSDKManageReviewQueryCenterReview.codes;
CodesMap[ErrorRpcSDKManageReviewQuerySDKManageReview.method] = ErrorRpcSDKManageReviewQuerySDKManageReview.codes;
CodesMap[ErrorRpcSDKManageReviewReview.method] = ErrorRpcSDKManageReviewReview.codes;
CodesMap[ErrorRpcSDKManageSmsRequestLoginVerifyCodeWithUserName.method] = ErrorRpcSDKManageSmsRequestLoginVerifyCodeWithUserName.codes;
CodesMap[ErrorRpcSDKManageSmsRequestVerify.method] = ErrorRpcSDKManageSmsRequestVerify.codes;
CodesMap[ErrorRpcSDKManageSystemAlarmDelete.method] = ErrorRpcSDKManageSystemAlarmDelete.codes;
CodesMap[ErrorRpcSDKManageSystemAlarmDetail.method] = ErrorRpcSDKManageSystemAlarmDetail.codes;
CodesMap[ErrorRpcSDKManageSystemAlarmModify.method] = ErrorRpcSDKManageSystemAlarmModify.codes;
CodesMap[ErrorRpcSDKManageSystemAlarmQuery.method] = ErrorRpcSDKManageSystemAlarmQuery.codes;
CodesMap[ErrorRpcSDKManageSystemMessageDelete.method] = ErrorRpcSDKManageSystemMessageDelete.codes;
CodesMap[ErrorRpcSDKManageSystemMessageMark.method] = ErrorRpcSDKManageSystemMessageMark.codes;
CodesMap[ErrorRpcSDKManageSystemMessageQuery.method] = ErrorRpcSDKManageSystemMessageQuery.codes;
CodesMap[ErrorRpcSDKManageSystemMessageSend.method] = ErrorRpcSDKManageSystemMessageSend.codes;
CodesMap[ErrorRpcSDKManageSystemNoticeAdd.method] = ErrorRpcSDKManageSystemNoticeAdd.codes;
CodesMap[ErrorRpcSDKManageSystemNoticeDelete.method] = ErrorRpcSDKManageSystemNoticeDelete.codes;
CodesMap[ErrorRpcSDKManageSystemNoticeModify.method] = ErrorRpcSDKManageSystemNoticeModify.codes;
CodesMap[ErrorRpcSDKManageSystemNoticeQuery.method] = ErrorRpcSDKManageSystemNoticeQuery.codes;
CodesMap[ErrorRpcSDKManageTokenGetAccessToken.method] = ErrorRpcSDKManageTokenGetAccessToken.codes;
CodesMap[ErrorRpcSDKManageTokenGetRefreshToken.method] = ErrorRpcSDKManageTokenGetRefreshToken.codes;
CodesMap[ErrorRpcSDKManageTransactionConsumptionExport.method] = ErrorRpcSDKManageTransactionConsumptionExport.codes;
CodesMap[ErrorRpcSDKManageTransactionMakeUpPosMachineRecharge.method] = ErrorRpcSDKManageTransactionMakeUpPosMachineRecharge.codes;
CodesMap[ErrorRpcSDKManageTransactionQuery.method] = ErrorRpcSDKManageTransactionQuery.codes;
CodesMap[ErrorRpcSDKManageTransactionRechargeReconcilation.method] = ErrorRpcSDKManageTransactionRechargeReconcilation.codes;
CodesMap[ErrorRpcSDKManageUserAdd.method] = ErrorRpcSDKManageUserAdd.codes;
CodesMap[ErrorRpcSDKManageUserAddPermission.method] = ErrorRpcSDKManageUserAddPermission.codes;
CodesMap[ErrorRpcSDKManageUserDelete.method] = ErrorRpcSDKManageUserDelete.codes;
CodesMap[ErrorRpcSDKManageUserDeletePermission.method] = ErrorRpcSDKManageUserDeletePermission.codes;
CodesMap[ErrorRpcSDKManageUserFreeze.method] = ErrorRpcSDKManageUserFreeze.codes;
CodesMap[ErrorRpcSDKManageUserGetPermission.method] = ErrorRpcSDKManageUserGetPermission.codes;
CodesMap[ErrorRpcSDKManageUserModifyPassword.method] = ErrorRpcSDKManageUserModifyPassword.codes;
CodesMap[ErrorRpcSDKManageUserQuery.method] = ErrorRpcSDKManageUserQuery.codes;
CodesMap[ErrorRpcSDKManageUserResetLoginPasswordWithSms.method] = ErrorRpcSDKManageUserResetLoginPasswordWithSms.codes;
CodesMap[ErrorRpcSDKManageUserUnFreeze.method] = ErrorRpcSDKManageUserUnFreeze.codes;

export default CodesMap;
