import { default as ErrorRpcSDKManageOrganizationQuery } from './ErrorRpcSDKManageOrganizationQuery';
import { default as ErrorRpcSDKManageRoleUnFreeze } from './ErrorRpcSDKManageRoleUnFreeze';
import { default as ErrorRpcSDKManageRoleQuery } from './ErrorRpcSDKManageRoleQuery';
import { default as ErrorRpcSDKManageRoleModify } from './ErrorRpcSDKManageRoleModify';
import { default as ErrorRpcSDKManageRoleAdd } from './ErrorRpcSDKManageRoleAdd';
import { default as ErrorRpcSDKManageRoleFreeze } from './ErrorRpcSDKManageRoleFreeze';
import { default as ErrorRpcSDKManageAuthLogout } from './ErrorRpcSDKManageAuthLogout';
import { default as ErrorRpcSDKManageAuthLoginWithVerifyCode } from './ErrorRpcSDKManageAuthLoginWithVerifyCode';
import { default as ErrorRpcSDKManageAuthGetLoginVerifyCode } from './ErrorRpcSDKManageAuthGetLoginVerifyCode';
import { default as ErrorRpcSDKManageAuthGenerateUUID } from './ErrorRpcSDKManageAuthGenerateUUID';
import { default as ErrorRpcSDKManageFactorageModify } from './ErrorRpcSDKManageFactorageModify';
import { default as ErrorRpcSDKManageFactorageQueryDetail } from './ErrorRpcSDKManageFactorageQueryDetail';
import { default as ErrorRpcSDKManageMiniPayPlatformQuery } from './ErrorRpcSDKManageMiniPayPlatformQuery';
import { default as ErrorRpcSDKManageMemberResetLoginPassword } from './ErrorRpcSDKManageMemberResetLoginPassword';
import { default as ErrorRpcSDKManageMemberUnFreeze } from './ErrorRpcSDKManageMemberUnFreeze';
import { default as ErrorRpcSDKManageMemberQuery } from './ErrorRpcSDKManageMemberQuery';
import { default as ErrorRpcSDKManageMemberRegister } from './ErrorRpcSDKManageMemberRegister';
import { default as ErrorRpcSDKManageMemberFreeze } from './ErrorRpcSDKManageMemberFreeze';
import { default as ErrorRpcSDKManageMemberResetPayPassword } from './ErrorRpcSDKManageMemberResetPayPassword';
import { default as ErrorRpcSDKManageUserUnFreeze } from './ErrorRpcSDKManageUserUnFreeze';
import { default as ErrorRpcSDKManageUserQuery } from './ErrorRpcSDKManageUserQuery';
import { default as ErrorRpcSDKManageUserAddSystemUser } from './ErrorRpcSDKManageUserAddSystemUser';
import { default as ErrorRpcSDKManageUserModify } from './ErrorRpcSDKManageUserModify';
import { default as ErrorRpcSDKManageUserResetPassword } from './ErrorRpcSDKManageUserResetPassword';
import { default as ErrorRpcSDKManageUserFreeze } from './ErrorRpcSDKManageUserFreeze';
import { default as ErrorRpcSDKManageReviewRefuse } from './ErrorRpcSDKManageReviewRefuse';
import { default as ErrorRpcSDKManageReviewReview } from './ErrorRpcSDKManageReviewReview';
import { default as ErrorRpcSDKManageQuotaTransactionConsumeExport } from './ErrorRpcSDKManageQuotaTransactionConsumeExport';
import { default as ErrorRpcSDKManageQuotaTransactionConsumeQuery } from './ErrorRpcSDKManageQuotaTransactionConsumeQuery';
import { default as ErrorRpcSDKManageQuotaTransactionRechargeExport } from './ErrorRpcSDKManageQuotaTransactionRechargeExport';
import { default as ErrorRpcSDKManageQuotaTransactionRechargeQuery } from './ErrorRpcSDKManageQuotaTransactionRechargeQuery';
import { default as ErrorRpcSDKManageQuotaUnFreeze } from './ErrorRpcSDKManageQuotaUnFreeze';
import { default as ErrorRpcSDKManageQuotaQuery } from './ErrorRpcSDKManageQuotaQuery';
import { default as ErrorRpcSDKManageQuotaModifyOverDraft } from './ErrorRpcSDKManageQuotaModifyOverDraft';
import { default as ErrorRpcSDKManageQuotaFreeze } from './ErrorRpcSDKManageQuotaFreeze';
import { default as ErrorRpcSDKManageQuotaAddition } from './ErrorRpcSDKManageQuotaAddition';
import { default as ErrorRpcSDKManageMerchantMemberAddMerchantMember } from './ErrorRpcSDKManageMerchantMemberAddMerchantMember';
import { default as ErrorRpcSDKManageMerchantMemberQueryMerchantMemberDetail } from './ErrorRpcSDKManageMerchantMemberQueryMerchantMemberDetail';
import { default as ErrorRpcSDKManageMerchantMemberQuery } from './ErrorRpcSDKManageMerchantMemberQuery';
import { default as ErrorRpcSDKManagePermissionQuery } from './ErrorRpcSDKManagePermissionQuery';
import { default as ErrorRpcSDKManageMerchantUnFreeze } from './ErrorRpcSDKManageMerchantUnFreeze';
import { default as ErrorRpcSDKManageMerchantQuery } from './ErrorRpcSDKManageMerchantQuery';
import { default as ErrorRpcSDKManageMerchantModifyMerchant } from './ErrorRpcSDKManageMerchantModifyMerchant';
import { default as ErrorRpcSDKManageMerchantAddMerchant } from './ErrorRpcSDKManageMerchantAddMerchant';
import { default as ErrorRpcSDKManageMerchantFreeze } from './ErrorRpcSDKManageMerchantFreeze';

let CodesMap = {};
CodesMap[ErrorRpcSDKManageOrganizationQuery.method] = ErrorRpcSDKManageOrganizationQuery.codes;
CodesMap[ErrorRpcSDKManageRoleUnFreeze.method] = ErrorRpcSDKManageRoleUnFreeze.codes;
CodesMap[ErrorRpcSDKManageRoleQuery.method] = ErrorRpcSDKManageRoleQuery.codes;
CodesMap[ErrorRpcSDKManageRoleModify.method] = ErrorRpcSDKManageRoleModify.codes;
CodesMap[ErrorRpcSDKManageRoleAdd.method] = ErrorRpcSDKManageRoleAdd.codes;
CodesMap[ErrorRpcSDKManageRoleFreeze.method] = ErrorRpcSDKManageRoleFreeze.codes;
CodesMap[ErrorRpcSDKManageAuthLogout.method] = ErrorRpcSDKManageAuthLogout.codes;
CodesMap[ErrorRpcSDKManageAuthLoginWithVerifyCode.method] = ErrorRpcSDKManageAuthLoginWithVerifyCode.codes;
CodesMap[ErrorRpcSDKManageAuthGetLoginVerifyCode.method] = ErrorRpcSDKManageAuthGetLoginVerifyCode.codes;
CodesMap[ErrorRpcSDKManageAuthGenerateUUID.method] = ErrorRpcSDKManageAuthGenerateUUID.codes;
CodesMap[ErrorRpcSDKManageFactorageModify.method] = ErrorRpcSDKManageFactorageModify.codes;
CodesMap[ErrorRpcSDKManageFactorageQueryDetail.method] = ErrorRpcSDKManageFactorageQueryDetail.codes;
CodesMap[ErrorRpcSDKManageMiniPayPlatformQuery.method] = ErrorRpcSDKManageMiniPayPlatformQuery.codes;
CodesMap[ErrorRpcSDKManageMemberResetLoginPassword.method] = ErrorRpcSDKManageMemberResetLoginPassword.codes;
CodesMap[ErrorRpcSDKManageMemberUnFreeze.method] = ErrorRpcSDKManageMemberUnFreeze.codes;
CodesMap[ErrorRpcSDKManageMemberQuery.method] = ErrorRpcSDKManageMemberQuery.codes;
CodesMap[ErrorRpcSDKManageMemberRegister.method] = ErrorRpcSDKManageMemberRegister.codes;
CodesMap[ErrorRpcSDKManageMemberFreeze.method] = ErrorRpcSDKManageMemberFreeze.codes;
CodesMap[ErrorRpcSDKManageMemberResetPayPassword.method] = ErrorRpcSDKManageMemberResetPayPassword.codes;
CodesMap[ErrorRpcSDKManageUserUnFreeze.method] = ErrorRpcSDKManageUserUnFreeze.codes;
CodesMap[ErrorRpcSDKManageUserQuery.method] = ErrorRpcSDKManageUserQuery.codes;
CodesMap[ErrorRpcSDKManageUserAddSystemUser.method] = ErrorRpcSDKManageUserAddSystemUser.codes;
CodesMap[ErrorRpcSDKManageUserModify.method] = ErrorRpcSDKManageUserModify.codes;
CodesMap[ErrorRpcSDKManageUserResetPassword.method] = ErrorRpcSDKManageUserResetPassword.codes;
CodesMap[ErrorRpcSDKManageUserFreeze.method] = ErrorRpcSDKManageUserFreeze.codes;
CodesMap[ErrorRpcSDKManageReviewRefuse.method] = ErrorRpcSDKManageReviewRefuse.codes;
CodesMap[ErrorRpcSDKManageReviewReview.method] = ErrorRpcSDKManageReviewReview.codes;
CodesMap[ErrorRpcSDKManageQuotaTransactionConsumeExport.method] = ErrorRpcSDKManageQuotaTransactionConsumeExport.codes;
CodesMap[ErrorRpcSDKManageQuotaTransactionConsumeQuery.method] = ErrorRpcSDKManageQuotaTransactionConsumeQuery.codes;
CodesMap[ErrorRpcSDKManageQuotaTransactionRechargeExport.method] = ErrorRpcSDKManageQuotaTransactionRechargeExport.codes;
CodesMap[ErrorRpcSDKManageQuotaTransactionRechargeQuery.method] = ErrorRpcSDKManageQuotaTransactionRechargeQuery.codes;
CodesMap[ErrorRpcSDKManageQuotaUnFreeze.method] = ErrorRpcSDKManageQuotaUnFreeze.codes;
CodesMap[ErrorRpcSDKManageQuotaQuery.method] = ErrorRpcSDKManageQuotaQuery.codes;
CodesMap[ErrorRpcSDKManageQuotaModifyOverDraft.method] = ErrorRpcSDKManageQuotaModifyOverDraft.codes;
CodesMap[ErrorRpcSDKManageQuotaFreeze.method] = ErrorRpcSDKManageQuotaFreeze.codes;
CodesMap[ErrorRpcSDKManageQuotaAddition.method] = ErrorRpcSDKManageQuotaAddition.codes;
CodesMap[ErrorRpcSDKManageMerchantMemberAddMerchantMember.method] = ErrorRpcSDKManageMerchantMemberAddMerchantMember.codes;
CodesMap[ErrorRpcSDKManageMerchantMemberQueryMerchantMemberDetail.method] = ErrorRpcSDKManageMerchantMemberQueryMerchantMemberDetail.codes;
CodesMap[ErrorRpcSDKManageMerchantMemberQuery.method] = ErrorRpcSDKManageMerchantMemberQuery.codes;
CodesMap[ErrorRpcSDKManagePermissionQuery.method] = ErrorRpcSDKManagePermissionQuery.codes;
CodesMap[ErrorRpcSDKManageMerchantUnFreeze.method] = ErrorRpcSDKManageMerchantUnFreeze.codes;
CodesMap[ErrorRpcSDKManageMerchantQuery.method] = ErrorRpcSDKManageMerchantQuery.codes;
CodesMap[ErrorRpcSDKManageMerchantModifyMerchant.method] = ErrorRpcSDKManageMerchantModifyMerchant.codes;
CodesMap[ErrorRpcSDKManageMerchantAddMerchant.method] = ErrorRpcSDKManageMerchantAddMerchant.codes;
CodesMap[ErrorRpcSDKManageMerchantFreeze.method] = ErrorRpcSDKManageMerchantFreeze.codes;

export default CodesMap;
